name: Docs

on:
  push:
    branches: ['main']
    paths:
      - '**/package.json'
      - 'lib/**'
      - '.github/workflows/docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - run: yarn install --immutable
    - run: yarn docs
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'ci: generate docs'
